[package]
name = "sbi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Terminal Graphics
ratatui = "*"
crossterm = { version = "*", features = ["event-stream"] }

# Tui Widgets
tui-textarea = "0.4.0"

# Directory Management
directories = "5.0"

# Error Management
anyhow = "1.0"
thiserror = "1.0"

# Json Parsing
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rustc-hash = "1.1"

# Itertools
itertools = "0.12.1"

# Async
tokio = { version = "1.36", features = ["full"] }
tokio-util = "0.7"
futures = "0.3"

# Cli Tools
clap = { version = "4.5", features = ["derive"] }
clap_derive = "4.5"

# IPC
interprocess = { version = "1.2", features = ["tokio_support"] }

# Web Requests
reqwest = {version="0.12", features = ["json"]}

# Logging
log = "0.4"
flexi_logger = "0.28.0"
